# Builds the canonical 404 apparel print file from Maurice's 2026-09-23 reference. The current sticker master is intentionally generated by rebuild_sticker_hierarchy_1p25.py so all five individual stickers retain their approved 1.25x hierarchy.
import sys; sys.path.insert(0,'tools')
import make_print_file as m
from PIL import Image, ImageFont, ImageDraw
# Proportions measured off Maurice's 2026-09-23 reference, as fractions of bar width B.
R=dict(n404_w=0.2799, l2_w=0.7732, gap1=0.0642, gap2=0.0216, bar_h=0.0166, gap_mark=0.0510, mark_w=0.140)
def build(out,width,sticker):
    serif=m.font_path("Bodoni Moda",None,"BodoniModa-Regular.ttf")
    col={k:tuple(int(v.lstrip('#')[i:i+2],16) for i in (0,2,4)) for k,v in m.INK_LIGHT.items()}
    pad=width*0.045; B=width-2*pad
    f1=m._fit(ImageFont,serif,"404",R['n404_w']*B,'w'); f2=m._fit(ImageFont,serif,"STRAIGHT NOT FOUND",R['l2_w']*B,'w')
    h1=f1.getbbox("404"); h1=h1[3]-h1[1]; h2=f2.getbbox("STRAIGHT NOT FOUND"); h2=h2[3]-h2[1]
    y1=pad; y2=y1+h1+R['gap1']*B; yb=y2+h2+R['gap2']*B; bh=R['bar_h']*B
    fm=None; bottom=yb+bh
    if sticker:
        fm=m._fit(ImageFont,serif,"FÆBRIQ",R['mark_w']*B,'w'); hm=fm.getbbox("FÆBRIQ"); hm=hm[3]-hm[1]
        ym=yb+bh+R['gap_mark']*B; bottom=ym+hm
    im=Image.new('RGBA',(width,int(round(bottom+pad))),(0,0,0,0)); cx=width/2
    m._draw_reinforced(im,cx,y1,"404",f1,col['text']); m._draw_reinforced(im,cx,y2,"STRAIGHT NOT FOUND",f2,col['text'])
    d=ImageDraw.Draw(im); sw=m.SRC['stripe_frac']*B; gap=m.SRC['gap_frac']*B
    for i,c in enumerate(m.CIRCUIT): x0=pad+i*(sw+gap); d.rectangle([x0,yb,x0+sw,yb+bh],fill=c)
    if sticker: m._draw_reinforced(im,cx,ym,"FÆBRIQ",fm,col['mark'])
    im.save(out,'PNG',dpi=(300,300)); print(out,im.size)
build('assets/print-art/404-straight-not-found-v3-light-4500.png',4500,False)
